#!/usr/bin/python3

import modules.cli as cli
import modules.cli.command as cmd
import argparse as ap


def main() -> None:
    parser: ap.ArgumentParser = cli.create("Gerenciador de Senhas")
    args: ap.Namespace = cli.get_args(parser)
    cmd.resolve(parser, args)

if __name__ == "__main__":
    main()
